# Generated by Django 6.0 on 2026-03-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closure_reason',
            field=models.CharField(blank=True, default='', help_text='Reason shown to customers when manually closed', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_manually_closed',
            field=models.BooleanField(default=False, help_text='Admin can manually close the restaurant'),
        ),
    ]
