# Generated by Django 6.0.3 on 2026-03-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('completed_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_orders', models.PositiveIntegerField(default=0)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('service_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discounts_given', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('top_selling_items', models.JSONField(blank=True, default=list)),
                ('payment_method_breakdown', models.JSONField(blank=True, default=dict)),
                ('hourly_order_counts', models.JSONField(blank=True, default=dict)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='tenants.restaurant')),
            ],
            options={
                'verbose_name_plural': 'Daily summaries',
                'ordering': ['-date'],
                'unique_together': {('restaurant', 'date')},
            },
        ),
    ]
