# Generated by Django 6.0.3 on 2026-03-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Customer can add a note')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_waiter_calls', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='tenants.restaurant')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='tenants.table')),
                ('table_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.tablesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.CharField(blank=True, help_text='Broadcast to all users with this role', max_length=20)),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('order_status', 'Order Status Update'), ('waiter_call', 'Waiter Call'), ('payment', 'Payment'), ('system', 'System')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'recipient', 'is_read'], name='notificatio_restaur_aa8580_idx'), models.Index(fields=['restaurant', 'target_role', 'is_read'], name='notificatio_restaur_4387d3_idx')],
            },
        ),
    ]
